# Generated by Django 4.1 on 2022-09-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_free_consulation_data_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='free_consulation',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='free_consulation',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
