# Generated by Django 4.1 on 2022-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_full_name_free_consulation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_create', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
