# Generated by Django 4.1 on 2022-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_alter_comment_email_alter_comment_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
