# Generated by Django 4.1 on 2022-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_comment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(default='some string', upload_to='user_profile'),
        ),
    ]
